kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: helpinghands-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helpinghandsBackend
  template:
    metadata:
      labels:
        app: helpinghandsBackend
    spec:
      containers:
        - name: helpinghands-backend
          image: jayvaghela0304/helpinghands-backend:v1
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL