kind: Service
apiVersion: v1
metadata: 
  name: frontend-service
  namespace: helpinghands-ns

spec:
  selector:
    app: helpinghandsFrontend 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP